---
version: '2.1'

services:
  snl-frontend:
    build:
      context: .
    image: snl-frontend
    container_name: snl-frontend
    environment:
      - SNL_API_URL=http://localhost:8090
      - SNL_NOTES_URL=http://localhost:8093
      - PORT=8080
    ports:
      - 8094:8080
    networks:
      - snl-network
networks:
  snl-network:
    driver: bridge
    name: snl-network

