---
version: '3'

services:
  snl-front:
    build:
      context: .
    image: snl-frontend
    container_name: snl-frontend
    environment:
      - SNL_API_URL=http://localhost:8090
      - SNL_NOTES_URL=http://localhost:8093
      - PORT=8080
    ports:
      - 8094:80
