apiVersion: v1
kind: ConfigMap
metadata:
  name: ${SERVICE_NAME}-config
  namespace: ${NAMESPACE}
data:
  SNL_API_URL: "http://snl-api-aat.service.core-compute-aat.internal"
  SNL_NOTES_URL: "http://snl-notes-aat.service.core-compute-aat.internal"
