apiVersion: v1
kind: ConfigMap
metadata:
  name: ${SERVICE_NAME}-config
  namespace: ${NAMESPACE}
data:
  SNL_API_URL: "http://snl-api-saat.service.core-compute-saat.internal"
  SNL_NOTES_URL: "http://snl-notes-saat.service.core-compute-saat.internal"
